# Generated by Django 3.1 on 2024-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Interest',
            field=models.ManyToManyField(to='post.Interest'),
        ),
    ]
